### 1. Environment Verification 



In [1]:
import torch
print("PyTorch version:", torch.__version__)
print("MPS backend built?  ", torch.backends.mps.is_built())
print("MPS available?      ", torch.backends.mps.is_available())

# quick device test
device = torch.device("mps")
x = torch.randn(2,2).to(device)
print("Tensor device:", x.device)

PyTorch version: 2.6.0
MPS backend built?   True
MPS available?       True
Tensor device: mps:0


### 2. Device‐Selection Boilerplate 



In [2]:
import torch

# 1) Check for MPS support (Apple GPU)
if torch.backends.mps.is_available():
    device = torch.device("mps")    # GPU
    print("Running on MPS (GPU)")
else:
    device = torch.device("cpu")    # CPU
    print("Running on CPU")



Running on MPS (GPU)


In [3]:
## testing torch 

x= torch.rand(5,3)
print(x)

tensor([[0.5241, 0.5252, 0.6989],
        [0.7180, 0.7311, 0.8910],
        [0.4919, 0.8216, 0.3326],
        [0.8718, 0.5150, 0.8954],
        [0.2859, 0.9136, 0.7167]])


### Importing relevant libraries 


In [4]:
import pandas as pd 
import numpy 
import matplotlib.pyplot

### Introduction to Tensors 

#### i. Creating Tensors Manually

A tensor is a numeric representation of data. In python, we have quite a variety of tensors:

- Scalar: These a zero dimension arrays or they have only magnitude 
- Vectors: These are 1-day array or these have magnitude and direction
- Matrix: These are 2-d arrays or these are linear transformations or moves in the X and Y direction or even 3d coordinates sometime
- Tensors: While the above are tensors, we usually refer to tensors are multi-dimensional arrays 

We will take a look at how to create each in Pytorch and we usually create this using torch.tensor()

In [5]:
## creating a scalar 

scalar= torch.tensor(7)

In [6]:

print(f"The value of the scalar is {scalar}")
print(f"The item present in the scalar is {scalar.item()}")
print(f"The dimension of the scalar is {scalar.ndim}")

The value of the scalar is 7
The item present in the scalar is 7
The dimension of the scalar is 0


In [7]:
## creating a vector 

vector= torch.tensor([7,7])


In [8]:

print(f"The value of the vector is {vector.tolist()}")
print(f"The dimension of the vector is {vector.ndim}")
print(f"The shape of the vector is {vector.shape}")



The value of the vector is [7, 7]
The dimension of the vector is 1
The shape of the vector is torch.Size([2])


In [9]:
##creating MATRIX

MATRIX= torch.tensor([[7,9], [10,11]])




In [10]:

print(f"The value of the vector is {MATRIX}")
print(f"The dimension of the vector is {MATRIX.ndim}")
print(f"The shape of the  matrix is {MATRIX.shape}")

The value of the vector is tensor([[ 7,  9],
        [10, 11]])
The dimension of the vector is 2
The shape of the  matrix is torch.Size([2, 2])


In [11]:
MATRIX[1]

tensor([10, 11])

In [12]:
###TENSOR

TENSOR= torch.tensor([[[1,2,3,4,],[5,6,7,8],[9,10,11,2]]])

In [13]:
print(f"The value of the vector is {TENSOR}")
print(f"The dimension of the vector is {TENSOR.ndim}")
print(f"The shape of the  matrix is {TENSOR.shape}")


The value of the vector is tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11,  2]]])
The dimension of the vector is 3
The shape of the  matrix is torch.Size([1, 3, 4])


#### ii. Generating Random Tensors

- This is important as in neural networks, this allows us to assign random weights to our nerual networks, and then adjust the random numbers to better represent the data
- To create a random tensor, we use the torch.rand and we spcify the number of rows, columns, depth(if 3d) and others with the numbers you input separated by a comma. 
- Please note, while creating your random tensors, the more numbers separated by a comma, the more dimension you add

In [14]:
##creating the random tensor in various dimensions

random_tensor_2d= torch.rand(3,4)
random_tensor_3d= torch.rand(3,4,4)
random_tensor_4d= torch.rand(3,4,4,5)

In [15]:
print(random_tensor_2d)
print(random_tensor_3d)
print(random_tensor_4d)


tensor([[0.4852, 0.5467, 0.4983, 0.4698],
        [0.4621, 0.8518, 0.6378, 0.8971],
        [0.1990, 0.0430, 0.6494, 0.1732]])
tensor([[[0.1993, 0.2713, 0.3496, 0.5201],
         [0.5649, 0.6697, 0.3590, 0.2970],
         [0.9096, 0.2562, 0.2980, 0.8302],
         [0.2144, 0.1365, 0.0077, 0.3371]],

        [[0.3487, 0.4855, 0.8208, 0.5824],
         [0.8617, 0.4473, 0.7042, 0.6486],
         [0.9583, 0.8971, 0.7740, 0.2501],
         [0.8133, 0.0335, 0.3756, 0.0494]],

        [[0.9023, 0.2461, 0.9904, 0.2282],
         [0.8455, 0.6527, 0.3542, 0.6737],
         [0.9753, 0.8877, 0.8925, 0.9533],
         [0.3746, 0.5614, 0.4980, 0.3928]]])
tensor([[[[0.1011, 0.5028, 0.6171, 0.1331, 0.2831],
          [0.8947, 0.7158, 0.4195, 0.3658, 0.5073],
          [0.0367, 0.3864, 0.2363, 0.7371, 0.7482],
          [0.0632, 0.2016, 0.0878, 0.6703, 0.4360]],

         [[0.6208, 0.5633, 0.0556, 0.8235, 0.1631],
          [0.8506, 0.8566, 0.0691, 0.0228, 0.3286],
          [0.3619, 0.8117, 0.3149, 0.

In [16]:
print(random_tensor_2d.ndim)
print(random_tensor_3d.ndim)
print(random_tensor_4d.ndim)

##sp from this code, it means we specify the dimension of the 

2
3
4


### iii.Generating Zeros and Ones

In [17]:
zeros= torch.zeros((3,4))
print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [18]:
ones= torch.ones((5,6))
print(ones)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [19]:
arange_ten= torch.arange(5,20,2)
print(arange_ten)



tensor([ 5,  7,  9, 11, 13, 15, 17, 19])


In [20]:
##creating tensors like other tensors but with zeros 

ten_zeros= torch.zeros_like(arange_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0])


### Tensor Data Types 

- 32: Single Precision
- 16 bit: Half Precision

Top 3 Errors in Pytorch and Deep Learning: 

1. Tensor not right datatype
2. Tensor not right shape 
3. Tensor not on the right device

In [21]:
float_32_tensor= torch.tensor([2,3,4], dtype=torch.float32)
float_32_tensor.dtype



torch.float32

In [22]:
## to change the dtype

float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

### To get information from Tensor

In [23]:
## finding some details about tensor 

some_tensor= torch.rand((4,5))
some_tensor

tensor([[0.8410, 0.3610, 0.8895, 0.3536, 0.4903],
        [0.4227, 0.1400, 0.8536, 0.1629, 0.9681],
        [0.3486, 0.7222, 0.7141, 0.0631, 0.1488],
        [0.6391, 0.3087, 0.9752, 0.6452, 0.8846]])

## personal exercise 

### Q1 

i. Create a random tensor 3 rows and 4 columns, 

ii. Extract information such as it's size, it's device, and it's shape 

iii. Change the device from CPU to GPU  

iv. Also, change its dtype to float 16




##### i. Creating the tensor

In [24]:
rand_tens= torch.rand([3,4])


#### ii. Extracting Requested Data 

In [25]:
print(f"The Shape of this tensor is {rand_tens.shape}")
print(f"The Size of this tensor is {rand_tens.size()}")
print(f"The device of this tensor is {rand_tens.device}")
print(f"The datatype of this tensor is {rand_tens.dtype}")

The Shape of this tensor is torch.Size([3, 4])
The Size of this tensor is torch.Size([3, 4])
The device of this tensor is cpu
The datatype of this tensor is torch.float32


#### iii. Changing from CPU to mps 

In [26]:
mps= torch.device('mps')
rand_tens_mps=rand_tens.to(mps)


In [27]:
print(f"The device of this tensor is {rand_tens_mps.device}")


The device of this tensor is mps:0


#### iv. Changing its Dtype

In [28]:
rand_tens=rand_tens.to(torch.float16)
rand_tens.dtype

torch.float16

## Tensor Operations (Manipulating Tensors)

We can perform the following operations with tensors:

- Addition
- Substraction
- Multiplication
- Division
- Matrix Multiplicaton

In [29]:
## addition

t1= torch.tensor([2,3,4,10,15])

t1+10

tensor([12, 13, 14, 20, 25])

In [30]:
torch.add(t1, 20)

tensor([22, 23, 24, 30, 35])

In [31]:
### Substraction

t2= torch.tensor([7,8,3,2,1])

t2-5

tensor([ 2,  3, -2, -3, -4])

In [32]:
## multiplication

t3= torch.tensor([10,15,20,25])

t3*20

tensor([200, 300, 400, 500])

In [33]:
torch.mul(t3,10)

tensor([100, 150, 200, 250])

In [34]:
##division

t4= torch.tensor([60,70,90,20], dtype=torch.int32)
t4/10

tensor([6., 7., 9., 2.])

#### Matrix Multiplication

From linear algebra, we have 2 or 3 types of matrix multiplication:

- Hadaman product: element-wise multiplication where both matrices have the same shape 
- Matrix multiplication 
- Dot Product 
- Also note that for every shape (x,y), x is the rows, and y is the column-- this should help us later on 

In [35]:
### Hamdaman Product: This is similar to the usual multiplication we do; however, the shape of both tensors should the same

t11= torch.tensor([[2,4,5],[2,4,5], [7,8,9]])
t12= torch.tensor([[11,4,17],[9,4,5], [7,8,9]])

t11*t12

tensor([[22, 16, 85],
        [18, 16, 25],
        [49, 64, 81]])

In [36]:
import time

In [37]:
### Matrix Multiplication: The column of the first matrix  must be equal to that of the row of the last matrix  

t11= torch.tensor([[2,4,5],[2,4,5]])
t12= torch.tensor([[11,4,17],[9,4,5],[7,8,9]])

torch.matmul(t11,t12)

tensor([[93, 64, 99],
        [93, 64, 99]])

### Adjusting Tensor shapes with Transpose for Matrix Multiplications

- ***Note***: A tranpose switches the rows and makes them columns and makes the column rows 

In [38]:
tensor_A= torch.tensor([[34,5,6,3], [3,2,5,6], [7,8,9,10]])
tensor_B= torch.tensor([[4,5,6,3], [9,9,9,10], [12,8,9,10]])

In [39]:
##uncomment to run the code, it won't work, I am commenting it out to ensure I can run all cells later on

##code below

##torch.matmul(tensor_A,tensor_B)

- We will try to transpose tensor_B to change it's shape to 4,3.
- Remeber transpose makes the column rows and makes the rows column

In [40]:
## printing tensor_B and its shape 
print(tensor_B)
print(tensor_B.shape)


tensor([[ 4,  5,  6,  3],
        [ 9,  9,  9, 10],
        [12,  8,  9, 10]])
torch.Size([3, 4])


In [41]:
## printing tensor_B
print(tensor_B.T)
print(tensor_B.T.shape)

tensor([[ 4,  9, 12],
        [ 5,  9,  8],
        [ 6,  9,  9],
        [ 3, 10, 10]])
torch.Size([4, 3])


In [42]:
##now we will multiply tensor_a and the transpose of tensor_B
torch.matmul(tensor_A,tensor_B.T)

tensor([[206, 435, 532],
        [ 70, 150, 157],
        [152, 316, 329]])

## Tensor Aggregation:

In this section, we will take a look at how to find the: 

- Mean
- Min
- Max
- Sum and other values from a tensor

In [43]:
## Mean 

tensor_4_agg= torch.tensor([2,4,5,3], dtype=float)

In [44]:
tensor_mean= torch.mean(tensor_4_agg)
print(tensor_mean)

tensor(3.5000, dtype=torch.float64)


In [45]:
##finding the max

tensor_max= torch.max(tensor_4_agg)
print(tensor_max)

tensor(5., dtype=torch.float64)


In [46]:
##finding the sum
tensor_sum= torch.sum(tensor_4_agg)
print(tensor_sum)

tensor(14., dtype=torch.float64)


### Finding Positional Min (argmin) and Max (argmax)

- The argmin gives us the position (index) of the least value from a list of probabilities 
- The argmax gives us the position (index)  of the highest value from a list of probabilities 

In [47]:
##we will be using the tensor we created for aggregation for this 

tensor_4_agg

tensor([2., 4., 5., 3.], dtype=torch.float64)

In [48]:
tensor_4_agg.argmax()

tensor(2)

In [49]:
tensor_4_agg.argmin()

tensor(0)

### Reshaping, stacking, Squeezing, and Unsqueezing Tensors 

- Reshaping: Reshapes an input tensor to a defined shape 
- View- Return a view of an input tensor of a certain shpe but keep the same memory as the original tensor 
- Stacking- combines multiple tensors on top of each other or side by side 
- Squeeze: Removes all 1 dimension from a tensor 
- Unsqeeze: Add a 1 dimension to a target tensor 
- Permute: Return a view of input with dimensions permuted (swapped) in a certain way 

#### i. Reshaping 
Allows us to change the dimension of our tensor. Usually the row and column specification of the resphase should be multiples of the size of the tensor

In [51]:
tensor_A

tensor([[34,  5,  6,  3],
        [ 3,  2,  5,  6],
        [ 7,  8,  9, 10]])

In [57]:
torch.reshape(tensor_A, shape= (4,3))

tensor([[34,  5,  6],
        [ 3,  3,  2],
        [ 5,  6,  7],
        [ 8,  9, 10]])

In [63]:
 tensor_A.reshape(6,2)


tensor([[34,  5],
        [ 6,  3],
        [ 3,  2],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [64]:
 tensor_A.reshape(1,12)


tensor([[34,  5,  6,  3,  3,  2,  5,  6,  7,  8,  9, 10]])

#### Stacking

In [76]:
stack= torch.stack([tensor_A, tensor_B], dim=0)
stack

tensor([[[34,  5,  6,  3],
         [ 3,  2,  5,  6],
         [ 7,  8,  9, 10]],

        [[ 4,  5,  6,  3],
         [ 9,  9,  9, 10],
         [12,  8,  9, 10]]])

In [72]:
h_stack= torch.hstack([tensor_A, tensor_B])
h_stack

tensor([[34,  5,  6,  3,  4,  5,  6,  3],
        [ 3,  2,  5,  6,  9,  9,  9, 10],
        [ 7,  8,  9, 10, 12,  8,  9, 10]])

In [78]:
V_stack=torch.vstack([tensor_A, tensor_B])
V_stack

tensor([[34,  5,  6,  3],
        [ 3,  2,  5,  6],
        [ 7,  8,  9, 10],
        [ 4,  5,  6,  3],
        [ 9,  9,  9, 10],
        [12,  8,  9, 10]])

#### Squeezing and UnSqueezin

In [79]:
tensor_A

tensor([[34,  5,  6,  3],
        [ 3,  2,  5,  6],
        [ 7,  8,  9, 10]])

In [90]:
tensor_A.unsqueeze(dim=2)

tensor([[[34],
         [ 5],
         [ 6],
         [ 3]],

        [[ 3],
         [ 2],
         [ 5],
         [ 6]],

        [[ 7],
         [ 8],
         [ 9],
         [10]]])

In [108]:
torch.manual_seed(23)
t4= torch.rand(1,2,4,5)

print(f"The shape of {t4} is: {t4.shape}")

The shape of tensor([[[[0.4283, 0.2889, 0.4224, 0.3571, 0.9577],
          [0.1100, 0.2933, 0.9205, 0.5876, 0.1299],
          [0.6729, 0.1028, 0.7876, 0.5540, 0.4653],
          [0.2311, 0.2214, 0.3348, 0.4541, 0.2519]],

         [[0.6310, 0.1707, 0.3122, 0.1976, 0.5466],
          [0.0213, 0.9049, 0.8444, 0.9330, 0.2950],
          [0.4773, 0.4787, 0.3440, 0.6732, 0.6593],
          [0.1879, 0.4546, 0.1049, 0.7112, 0.7709]]]]) is: torch.Size([1, 2, 4, 5])


In [110]:
squeezed_t4= t4.squeeze()

print(f"The shape of {squeezed_t4} is: {squeezed_t4.shape}")

The shape of tensor([[[0.4283, 0.2889, 0.4224, 0.3571, 0.9577],
         [0.1100, 0.2933, 0.9205, 0.5876, 0.1299],
         [0.6729, 0.1028, 0.7876, 0.5540, 0.4653],
         [0.2311, 0.2214, 0.3348, 0.4541, 0.2519]],

        [[0.6310, 0.1707, 0.3122, 0.1976, 0.5466],
         [0.0213, 0.9049, 0.8444, 0.9330, 0.2950],
         [0.4773, 0.4787, 0.3440, 0.6732, 0.6593],
         [0.1879, 0.4546, 0.1049, 0.7112, 0.7709]]]) is: torch.Size([2, 4, 5])


- From above, the shapes are different 

In [ ]:
## unsqueeze: We will use the squeezed t4 as an exaample 

## the dim tells us the position to which we can add the new dimension of size 1, I will create an extra with the changed dim to demonstrate this 

unsqueezed_t4= squeezed_t4.unsqueeze(dim=3)
unsqueezed_t4_2= squeezed_t4.unsqueeze(dim=2)




In [120]:
##we will just print the shape to see how they shapes vary from the original tensor: 

print(f"The shape of t4 is: {t4.shape}")
print(f"The shape of squeezed_t4 is: {squeezed_t4.shape}")
print(f"The shape of unsqueezed_t4 is: {unsqueezed_t4.shape}")
print(f"The shape of unsqueezed_t4_2 is: {unsqueezed_t4_2.shape}")



The shape of t4 is: torch.Size([1, 2, 4, 5])
The shape of squeezed_t4 is: torch.Size([2, 4, 5])
The shape of unsqueezed_t4 is: torch.Size([2, 4, 5, 1])
The shape of unsqueezed_t4_2 is: torch.Size([2, 4, 1, 5])


#### Permutation 

- Permutation allows us to change the orientation of the values of a matrix 

In [ ]:
torch.manual_seed(33) ## to ensure consistency

x_original= torch.rand(size=(2,4,3))

x_permute= torch.permute(x_original, (2,0,1))

In [130]:
print(f"The original shape of x_original is {x_original.shape}")
print(f"The permute shape of x_original is {x_permute.shape}")



The original shape of x_original is torch.Size([2, 4, 3])
The permute shape of x_original is torch.Size([3, 2, 4])


### Indexing

- Indexing in Pytorch is simlar to indexing in Numpy

In [142]:
x= torch.arange(1,13).reshape(1,4,3)

x, x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9],
          [10, 11, 12]]]),
 torch.Size([1, 4, 3]))

Extract the following:

- First row 
- number 7, and 1
- second and third row 

In [151]:
##indexing the first row 

x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
##extracting numbers 7,

x[0][2][0]

tensor(7)

In [155]:
##extracting the number 11

x[0][3][1]

tensor(11)

In [156]:
##extracting the first two rows 

x[:,1:3]


tensor([[[4, 5, 6],
         [7, 8, 9]]])

### Pytorch, Tensors and Numpy 

This section focused on teaching how to get data from `numpy` and use it in `pytorch` or vice versa

- To use `Numpy` in `Pytorch`, you use the: `torch.from_numpy(ndarray)`
- To use `PyTorch` tensor, you use the `torch.Tensor.numpy()`

In [159]:
import numpy as np

np_array= np.array([[2,3,4,5], [2,4,23,2]])

print(np_array.dtype)

int64


In [ ]:
##changing a numpy array to a tensor 

np_array_tensor= torch.from_numpy(np_array)

In [162]:
print(f"The datatype of the numpy array is {np_array.dtype}.")
print(f"The datatype of the Pytorch tensor is {np_array_tensor.dtype}.")

The datatype of the numpy array is int64.
The datatype of the Pytorch tensor is torch.int64.


In [164]:
##changing a tensor to an array 

ten_to_np_array=torch.Tensor.numpy(tensor_A)

In [165]:
print(f"The datatype of the numpy array is {tensor_A.dtype}.")
print(f"The datatype of the Pytorch tensor is {ten_to_np_array.dtype}.")

The datatype of the numpy array is torch.int64.
The datatype of the Pytorch tensor is int64.


### Pytorch Reproducability 

- If you noticed I used some sort of `manual_seed` in some of my codes where I used the rand variable. Well this is because, I didn't want the value changing each time I run my code
- This is also important in cases where you want to share your code with others and ensure that you both have the same values  

In [169]:
torch.manual_seed(123)

tensor_static= torch.randn(2,3,4)



In [170]:
tensor_static

tensor([[[ 0.3374, -0.1778, -0.3035, -0.5880],
         [ 0.3486,  0.6603, -0.2196, -0.3792],
         [-0.1606, -0.4015,  0.6957, -1.8061]],

        [[ 1.8960, -0.1750,  1.3689, -1.6033],
         [-0.7849, -1.4096, -0.4076,  0.7953],
         [ 0.9985,  0.2212,  1.8319, -0.3378]]])

In [176]:
torch.randn(2,3,4)


tensor([[[-0.8484,  0.5323, -0.9344, -0.8431],
         [-0.1346,  0.4680, -0.7952, -0.9178],
         [ 1.3818, -0.0694, -0.7612,  0.2416]],

        [[-0.5878, -1.1506,  1.0164,  0.1234],
         [ 1.1311, -0.0858, -0.0597,  0.3553],
         [-1.4355,  0.0727,  0.1053, -1.0311]]])

In [174]:
torch.randn(2,3,4)


tensor([[[-0.5872,  1.1952, -1.2096, -0.5560],
         [-2.7202,  0.5421, -1.1541,  0.7763],
         [-1.2743,  0.4513, -0.2280,  0.9224]],

        [[ 0.2056, -0.4970,  0.5821,  0.2053],
         [-0.3018, -0.6703, -0.6171, -0.8334],
         [ 0.4839, -0.1349,  0.2119, -0.8714]]])

In [171]:
tensor_static

tensor([[[ 0.3374, -0.1778, -0.3035, -0.5880],
         [ 0.3486,  0.6603, -0.2196, -0.3792],
         [-0.1606, -0.4015,  0.6957, -1.8061]],

        [[ 1.8960, -0.1750,  1.3689, -1.6033],
         [-0.7849, -1.4096, -0.4076,  0.7953],
         [ 0.9985,  0.2212,  1.8319, -0.3378]]])

### Summary 
- So, we can see the tensor-static stays the same 
- But the second and third changes 
- The `torch.manual_seed` only affects the cell it is in 