### 1. Environment Verification 



In [1]:
import torch
print("PyTorch version:", torch.__version__)
print("MPS backend built?  ", torch.backends.mps.is_built())
print("MPS available?      ", torch.backends.mps.is_available())

# quick device test
device = torch.device("mps")
x = torch.randn(2,2).to(device)
print("Tensor device:", x.device)

PyTorch version: 2.6.0
MPS backend built?   True
MPS available?       True
Tensor device: mps:0


### 2. Device‐Selection Boilerplate 



In [2]:
import torch

# 1) Check for MPS support (Apple GPU)
if torch.backends.mps.is_available():
    device = torch.device("mps")    # GPU
    print("Running on MPS (GPU)")
else:
    device = torch.device("cpu")    # CPU
    print("Running on CPU")



Running on MPS (GPU)


In [5]:
## testing torch 

x= torch.rand(5,3)
print(x)

tensor([[0.4818, 0.8231, 0.8704],
        [0.3022, 0.5251, 0.7946],
        [0.7323, 0.8318, 0.7590],
        [0.2293, 0.3351, 0.1691],
        [0.9923, 0.7492, 0.0751]])


### Importing relevant libraries 


In [4]:
import pandas as pd 
import numpy 
import matplotlib.pyplot

### Introduction to Tensors 

#### i. Creating Tensors Manually

A tensor is a numeric representation of data. In python, we have quite a variety of tensors:

- Scalar: These a zero dimension arrays or they have only magnitude 
- Vectors: These are 1-day array or these have magnitude and direction
- Matrix: These are 2-d arrays or these are linear transformations or moves in the X and Y direction or even 3d coordinates sometime
- Tensors: While the above are tensors, we usually refer to tensors are multi-dimensional arrays 

We will take a look at how to create each in Pytorch and we usually create this using torch.tensor()

In [39]:
## creating a scalar 

scalar= torch.tensor(7)

In [40]:

print(f"The value of the scalar is {scalar}")
print(f"The item present in the scalar is {scalar.item()}")
print(f"The dimension of the scalar is {scalar.ndim}")

The value of the scalar is 7
The item present in the scalar is 7
The dimension of the scalar is 0


In [41]:
## creating a vector 

vector= torch.tensor([7,7])


In [42]:

print(f"The value of the vector is {vector.tolist()}")
print(f"The dimension of the vector is {vector.ndim}")
print(f"The shape of the vector is {vector.shape}")



The value of the vector is [7, 7]
The dimension of the vector is 1
The shape of the vector is torch.Size([2])


In [43]:
##creating MATRIX

MATRIX= torch.tensor([[7,9], [10,11]])




In [44]:

print(f"The value of the vector is {MATRIX}")
print(f"The dimension of the vector is {MATRIX.ndim}")
print(f"The shape of the  matrix is {MATRIX.shape}")

The value of the vector is tensor([[ 7,  9],
        [10, 11]])
The dimension of the vector is 2
The shape of the  matrix is torch.Size([2, 2])


In [45]:
MATRIX[1]

tensor([10, 11])

In [54]:
###TENSOR

TENSOR= torch.tensor([[[1,2,3,4,],[5,6,7,8],[9,10,11,2]]])

In [59]:
print(f"The value of the vector is {TENSOR}")
print(f"The dimension of the vector is {TENSOR.ndim}")
print(f"The shape of the  matrix is {TENSOR.shape}")


The value of the vector is tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11,  2]]])
The dimension of the vector is 3
The shape of the  matrix is torch.Size([1, 3, 4])


#### ii. Generating Random Tensors

- This is important as in neural networks, this allows us to assign random weights to our nerual networks, and then adjust the random numbers to better represent the data
- To create a random tensor, we use the torch.rand and we spcify the number of rows, columns, depth(if 3d) and others with the numbers you input separated by a comma. 
- Please note, while creating your random tensors, the more numbers separated by a comma, the more dimension you add

In [65]:
##creating the random tensor in various dimensions

random_tensor_2d= torch.rand(3,4)
random_tensor_3d= torch.rand(3,4,4)
random_tensor_4d= torch.rand(3,4,4,5)

In [ ]:
print(random_tensor_2d)
print(random_tensor_3d)
print(random_tensor_4d)


tensor([[0.7945, 0.5088, 0.6401, 0.2123],
        [0.0668, 0.0775, 0.5496, 0.4370],
        [0.8746, 0.8207, 0.6436, 0.2824]])
tensor([[[0.7361, 0.5814, 0.5717, 0.1909],
         [0.3999, 0.7976, 0.9136, 0.2951],
         [0.4707, 0.6237, 0.0490, 0.1563],
         [0.7508, 0.0609, 0.8108, 0.4064]],

        [[0.2171, 0.7884, 0.8488, 0.3094],
         [0.8159, 0.2981, 0.1114, 0.4722],
         [0.4591, 0.0801, 0.6409, 0.0837],
         [0.7682, 0.8262, 0.7094, 0.8126]],

        [[0.2351, 0.8312, 0.0132, 0.7684],
         [0.7529, 0.5908, 0.0025, 0.1607],
         [0.7540, 0.6242, 0.2675, 0.2648],
         [0.1019, 0.1110, 0.3880, 0.7250]]])
tensor([[[[0.3453, 0.1850, 0.4817, 0.5419, 0.9900],
          [0.9971, 0.8753, 0.7412, 0.2130, 0.8499],
          [0.9238, 0.2675, 0.1219, 0.8999, 0.2065],
          [0.9086, 0.6288, 0.2271, 0.5154, 0.8572]],

         [[0.6787, 0.9269, 0.1151, 0.0056, 0.2645],
          [0.2420, 0.6216, 0.8785, 0.0785, 0.8698],
          [0.6257, 0.7316, 0.3140, 0.

In [67]:
print(random_tensor_2d.ndim)
print(random_tensor_3d.ndim)
print(random_tensor_4d.ndim)

##sp from this code, it means we specify the dimension of the 

2
3
4


### iii.Generating Zeros and Ones

In [71]:
zeros= torch.zeros((3,4))
print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [72]:
ones= torch.ones((5,6))
print(ones)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [ ]:
arange_ten= torch.arange(5,20,2)
print(arange_ten)



tensor([ 5,  7,  9, 11, 13, 15, 17, 19])


In [78]:
##creating tensors like other tensors but with zeros 

ten_zeros= torch.zeros_like(arange_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0])


### Tensor Data Types 

- 32: Single Precision
- 16 bit: Half Precision

Top 3 Errors in Pytorch and Deep Learning: 

1. Tensor not right datatype
2. Tensor not right shape 
3. Tensor not on the right device

In [86]:
float_32_tensor= torch.tensor([2,3,4], dtype=torch.float32)
float_32_tensor.dtype



torch.float32

In [88]:
## to change the dtype

float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

### To get information from Tensor

In [90]:
## finding some details about tensor 

some_tensor= torch.rand((4,5))
some_tensor

tensor([[0.5413, 0.9370, 0.0518, 0.3847, 0.9391],
        [0.2870, 0.7553, 0.6051, 0.7492, 0.5664],
        [0.0328, 0.0718, 0.6321, 0.4209, 0.9764],
        [0.4567, 0.0847, 0.7013, 0.3506, 0.2286]])

## personal exercise 

### Q1 

i. Create a random tensor 3 rows and 4 columns, 

ii. Extract information such as it's size, it's device, and it's shape 

iii. Change the device from CPU to GPU  

iv. Also, change its dtype to float 16




##### i. Creating the tensor

In [ ]:
rand_tens= torch.rand([3,4])


#### ii. Extracting Requested Data 

In [93]:
print(f"The Shape of this tensor is {rand_tens.shape}")
print(f"The Size of this tensor is {rand_tens.size()}")
print(f"The device of this tensor is {rand_tens.device}")
print(f"The datatype of this tensor is {rand_tens.dtype}")

The Shape of this tensor is torch.Size([3, 4])
The Size of this tensor is torch.Size([3, 4])
The device of this tensor is cpu
The datatype of this tensor is torch.float32


#### iii. Changing from CPU to mps 

In [96]:
mps= torch.device('mps')
rand_tens_mps=rand_tens.to(mps)


In [97]:
print(f"The device of this tensor is {rand_tens_mps.device}")


The device of this tensor is mps:0


#### iv. Changing its Dtype

In [102]:
rand_tens=rand_tens.to(torch.float16)
rand_tens.dtype

torch.float16

## Tensor Operations (Manipulating Tensors)

We can perform the following operations with tensors:

- Addition
- Substraction
- Multiplication
- Division
- Matrix Multiplicaton

In [103]:
## addition

t1= torch.tensor([2,3,4,10,15])

t1+10

tensor([12, 13, 14, 20, 25])

In [112]:
torch.add(t1, 20)

tensor([22, 23, 24, 30, 35])

In [105]:
### Substraction

t2= torch.tensor([7,8,3,2,1])

t2-5

tensor([ 2,  3, -2, -3, -4])

In [106]:
## multiplication

t3= torch.tensor([10,15,20,25])

t3*20

tensor([200, 300, 400, 500])

In [111]:
torch.mul(t3,10)

tensor([100, 150, 200, 250])

In [110]:
##division

t4= torch.tensor([60,70,90,20], dtype=torch.int32)
t4/10

tensor([6., 7., 9., 2.])

#### Matrix Multiplication

From linear algebra, we have 2 types of matrix multiplication:

- Hadaman product: element-wise multiplication where both matrices have the same shape 
- Matrix multiplication 
- Dot Product 

In [118]:
### Hamdaman Product: This is similar to the usual multiplication we do; however, the shape of both tensors should the same

t11= torch.tensor([[2,4,5],[2,4,5], [7,8,9]])
t12= torch.tensor([[11,4,17],[9,4,5], [7,8,9]])

t11*t12

tensor([[22, 16, 85],
        [18, 16, 25],
        [49, 64, 81]])

In [120]:
### Matrix Multiplication

t11= torch.tensor([[2,4,5],[2,4,5], [7,8,9]])
t12= torch.tensor([[11,4,17],[9,4,5], [7,8,9]])

torch.matmul(t11,t12)

tensor([[ 93,  64,  99],
        [ 93,  64,  99],
        [212, 132, 240]])

device(type='cpu')