### 1. Environment Verification 



In [1]:
import torch
print("PyTorch version:", torch.__version__)
print("MPS backend built?  ", torch.backends.mps.is_built())
print("MPS available?      ", torch.backends.mps.is_available())

# quick device test
device = torch.device("mps")
x = torch.randn(2,2).to(device)
print("Tensor device:", x.device)

PyTorch version: 2.6.0
MPS backend built?   True
MPS available?       True
Tensor device: mps:0


### 2. Device‐Selection Boilerplate 



In [2]:
import torch

# 1) Check for MPS support (Apple GPU)
if torch.backends.mps.is_available():
    device = torch.device("mps")    # GPU
    print("Running on MPS (GPU)")
else:
    device = torch.device("cpu")    # CPU
    print("Running on CPU")



Running on MPS (GPU)


In [3]:
## testing torch 

x= torch.rand(5,3)
print(x)

tensor([[0.8036, 0.9714, 0.3210],
        [0.5894, 0.0324, 0.5549],
        [0.7921, 0.2235, 0.3529],
        [0.2912, 0.4008, 0.7134],
        [0.1320, 0.4779, 0.6763]])


### Importing relevant libraries 


In [4]:
import pandas as pd 
import numpy 
import matplotlib.pyplot

### Introduction to Tensors 

#### i. Creating Tensors Manually

A tensor is a numeric representation of data. In python, we have quite a variety of tensors:

- Scalar: These a zero dimension arrays or they have only magnitude 
- Vectors: These are 1-day array or these have magnitude and direction
- Matrix: These are 2-d arrays or these are linear transformations or moves in the X and Y direction or even 3d coordinates sometime
- Tensors: While the above are tensors, we usually refer to tensors are multi-dimensional arrays 

We will take a look at how to create each in Pytorch and we usually create this using torch.tensor()

In [5]:
## creating a scalar 

scalar= torch.tensor(7)

In [6]:

print(f"The value of the scalar is {scalar}")
print(f"The item present in the scalar is {scalar.item()}")
print(f"The dimension of the scalar is {scalar.ndim}")

The value of the scalar is 7
The item present in the scalar is 7
The dimension of the scalar is 0


In [7]:
## creating a vector 

vector= torch.tensor([7,7])


In [8]:

print(f"The value of the vector is {vector.tolist()}")
print(f"The dimension of the vector is {vector.ndim}")
print(f"The shape of the vector is {vector.shape}")



The value of the vector is [7, 7]
The dimension of the vector is 1
The shape of the vector is torch.Size([2])


In [9]:
##creating MATRIX

MATRIX= torch.tensor([[7,9], [10,11]])




In [10]:

print(f"The value of the vector is {MATRIX}")
print(f"The dimension of the vector is {MATRIX.ndim}")
print(f"The shape of the  matrix is {MATRIX.shape}")

The value of the vector is tensor([[ 7,  9],
        [10, 11]])
The dimension of the vector is 2
The shape of the  matrix is torch.Size([2, 2])


In [11]:
MATRIX[1]

tensor([10, 11])

In [12]:
###TENSOR

TENSOR= torch.tensor([[[1,2,3,4,],[5,6,7,8],[9,10,11,2]]])

In [13]:
print(f"The value of the vector is {TENSOR}")
print(f"The dimension of the vector is {TENSOR.ndim}")
print(f"The shape of the  matrix is {TENSOR.shape}")


The value of the vector is tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11,  2]]])
The dimension of the vector is 3
The shape of the  matrix is torch.Size([1, 3, 4])


#### ii. Generating Random Tensors

- This is important as in neural networks, this allows us to assign random weights to our nerual networks, and then adjust the random numbers to better represent the data
- To create a random tensor, we use the torch.rand and we spcify the number of rows, columns, depth(if 3d) and others with the numbers you input separated by a comma. 
- Please note, while creating your random tensors, the more numbers separated by a comma, the more dimension you add

In [14]:
##creating the random tensor in various dimensions

random_tensor_2d= torch.rand(3,4)
random_tensor_3d= torch.rand(3,4,4)
random_tensor_4d= torch.rand(3,4,4,5)

In [15]:
print(random_tensor_2d)
print(random_tensor_3d)
print(random_tensor_4d)


tensor([[0.6985, 0.7994, 0.7448, 0.7500],
        [0.7996, 0.3084, 0.7398, 0.2644],
        [0.5921, 0.4060, 0.0811, 0.3480]])
tensor([[[0.0416, 0.2335, 0.7052, 0.6153],
         [0.2737, 0.1121, 0.9500, 0.2446],
         [0.8460, 0.0089, 0.9619, 0.5810],
         [0.6085, 0.4067, 0.2134, 0.0542]],

        [[0.7453, 0.6991, 0.2764, 0.5405],
         [0.0659, 0.9120, 0.8163, 0.9384],
         [0.9551, 0.8511, 0.6724, 0.4554],
         [0.9972, 0.6807, 0.8506, 0.8105]],

        [[0.9038, 0.3076, 0.5778, 0.5667],
         [0.3709, 0.3680, 0.0484, 0.1890],
         [0.5377, 0.4145, 0.2317, 0.3499],
         [0.1906, 0.9279, 0.3065, 0.4196]]])
tensor([[[[0.8461, 0.8453, 0.7795, 0.8425, 0.6722],
          [0.7995, 0.6014, 0.5986, 0.2175, 0.6377],
          [0.9866, 0.3365, 0.5790, 0.7873, 0.1374],
          [0.3723, 0.2416, 0.6490, 0.3511, 0.5010]],

         [[0.3274, 0.5284, 0.8534, 0.7315, 0.5931],
          [0.6382, 0.2646, 0.5797, 0.1840, 0.9949],
          [0.3545, 0.8013, 0.8628, 0.

In [16]:
print(random_tensor_2d.ndim)
print(random_tensor_3d.ndim)
print(random_tensor_4d.ndim)

##sp from this code, it means we specify the dimension of the 

2
3
4


### iii.Generating Zeros and Ones

In [17]:
zeros= torch.zeros((3,4))
print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [18]:
ones= torch.ones((5,6))
print(ones)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [19]:
arange_ten= torch.arange(5,20,2)
print(arange_ten)



tensor([ 5,  7,  9, 11, 13, 15, 17, 19])


In [20]:
##creating tensors like other tensors but with zeros 

ten_zeros= torch.zeros_like(arange_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0])


### Tensor Data Types 

- 32: Single Precision
- 16 bit: Half Precision

Top 3 Errors in Pytorch and Deep Learning: 

1. Tensor not right datatype
2. Tensor not right shape 
3. Tensor not on the right device

In [21]:
float_32_tensor= torch.tensor([2,3,4], dtype=torch.float32)
float_32_tensor.dtype



torch.float32

In [22]:
## to change the dtype

float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

### To get information from Tensor

In [23]:
## finding some details about tensor 

some_tensor= torch.rand((4,5))
some_tensor

tensor([[0.5728, 0.3090, 0.1432, 0.8558, 0.1309],
        [0.1110, 0.2848, 0.3558, 0.6111, 0.7350],
        [0.3080, 0.8606, 0.3291, 0.8729, 0.9072],
        [0.4452, 0.8196, 0.8538, 0.7883, 0.7453]])

## personal exercise 

### Q1 

i. Create a random tensor 3 rows and 4 columns, 

ii. Extract information such as it's size, it's device, and it's shape 

iii. Change the device from CPU to GPU  

iv. Also, change its dtype to float 16




##### i. Creating the tensor

In [24]:
rand_tens= torch.rand([3,4])


#### ii. Extracting Requested Data 

In [25]:
print(f"The Shape of this tensor is {rand_tens.shape}")
print(f"The Size of this tensor is {rand_tens.size()}")
print(f"The device of this tensor is {rand_tens.device}")
print(f"The datatype of this tensor is {rand_tens.dtype}")

The Shape of this tensor is torch.Size([3, 4])
The Size of this tensor is torch.Size([3, 4])
The device of this tensor is cpu
The datatype of this tensor is torch.float32


#### iii. Changing from CPU to mps 

In [26]:
mps= torch.device('mps')
rand_tens_mps=rand_tens.to(mps)


In [27]:
print(f"The device of this tensor is {rand_tens_mps.device}")


The device of this tensor is mps:0


#### iv. Changing its Dtype

In [28]:
rand_tens=rand_tens.to(torch.float16)
rand_tens.dtype

torch.float16

## Tensor Operations (Manipulating Tensors)

We can perform the following operations with tensors:

- Addition
- Substraction
- Multiplication
- Division
- Matrix Multiplicaton

In [29]:
## addition

t1= torch.tensor([2,3,4,10,15])

t1+10

tensor([12, 13, 14, 20, 25])

In [30]:
torch.add(t1, 20)

tensor([22, 23, 24, 30, 35])

In [31]:
### Substraction

t2= torch.tensor([7,8,3,2,1])

t2-5

tensor([ 2,  3, -2, -3, -4])

In [32]:
## multiplication

t3= torch.tensor([10,15,20,25])

t3*20

tensor([200, 300, 400, 500])

In [33]:
torch.mul(t3,10)

tensor([100, 150, 200, 250])

In [34]:
##division

t4= torch.tensor([60,70,90,20], dtype=torch.int32)
t4/10

tensor([6., 7., 9., 2.])

#### Matrix Multiplication

From linear algebra, we have 2 or 3 types of matrix multiplication:

- Hadaman product: element-wise multiplication where both matrices have the same shape 
- Matrix multiplication 
- Dot Product 
- Also note that for every shape (x,y), x is the rows, and y is the column-- this should help us later on 

In [35]:
### Hamdaman Product: This is similar to the usual multiplication we do; however, the shape of both tensors should the same

t11= torch.tensor([[2,4,5],[2,4,5], [7,8,9]])
t12= torch.tensor([[11,4,17],[9,4,5], [7,8,9]])

t11*t12

tensor([[22, 16, 85],
        [18, 16, 25],
        [49, 64, 81]])

In [36]:
import time

In [37]:
### Matrix Multiplication: The column of the first matrix  must be equal to that of the row of the last matrix  

t11= torch.tensor([[2,4,5],[2,4,5]])
t12= torch.tensor([[11,4,17],[9,4,5],[7,8,9]])

torch.matmul(t11,t12)

tensor([[93, 64, 99],
        [93, 64, 99]])

### Adjusting Tensor shapes with Transpose for Matrix Multiplications

- ***Note***: A tranpose switches the rows and makes them columns and makes the column rows 

In [38]:
tensor_A= torch.tensor([[34,5,6,3], [3,2,5,6], [7,8,9,10]])
tensor_B= torch.tensor([[4,5,6,3], [9,9,9,10], [12,8,9,10]])

In [39]:
##uncomment to run the code, it won't work, I am commenting it out to ensure I can run all cells later on

##code below

##torch.matmul(tensor_A,tensor_B)

- We will try to transpose tensor_B to change it's shape to 4,3.
- Remeber transpose makes the column rows and makes the rows column

In [40]:
## printing tensor_B and its shape 
print(tensor_B)
print(tensor_B.shape)


tensor([[ 4,  5,  6,  3],
        [ 9,  9,  9, 10],
        [12,  8,  9, 10]])
torch.Size([3, 4])


In [41]:
## printing tensor_B
print(tensor_B.T)
print(tensor_B.T.shape)

tensor([[ 4,  9, 12],
        [ 5,  9,  8],
        [ 6,  9,  9],
        [ 3, 10, 10]])
torch.Size([4, 3])


In [42]:
##now we will multiply tensor_a and the transpose of tensor_B
torch.matmul(tensor_A,tensor_B.T)

tensor([[206, 435, 532],
        [ 70, 150, 157],
        [152, 316, 329]])

## Tensor Aggregation:

In this section, we will take a look at how to find the: 

- Mean
- Min
- Max
- Sum and other values from a tensor

In [43]:
## Mean 

tensor_4_agg= torch.tensor([2,4,5,3], dtype=float)

In [44]:
tensor_mean= torch.mean(tensor_4_agg)
print(tensor_mean)

tensor(3.5000, dtype=torch.float64)


In [45]:
##finding the max

tensor_max= torch.max(tensor_4_agg)
print(tensor_max)

tensor(5., dtype=torch.float64)


In [46]:
##finding the sum
tensor_sum= torch.sum(tensor_4_agg)
print(tensor_sum)

tensor(14., dtype=torch.float64)


### Finding Positional Min (argmin) and Max (argmax)

- The argmin gives us the position (index) of the least value from a list of probabilities 
- The argmax gives us the position (index)  of the highest value from a list of probabilities 

In [47]:
##we will be using the tensor we created for aggregation for this 

tensor_4_agg

tensor([2., 4., 5., 3.], dtype=torch.float64)

In [48]:
tensor_4_agg.argmax()

tensor(2)

In [49]:
tensor_4_agg.argmin()

tensor(0)

### Reshaping, stacking, Squeezing, and Unsqueezing Tensors 

- Reshaping: Reshapes an input tensor to a defined shape 
- View- Return a view of an input tensor of a certain shpe but keep the same memory as the original tensor 
- Stacking- combines multiple tensors on top of each other or side by side 
- Squeeze: Removes all 1 dimension from a tensor 
- Unsqeeze: Add a 1 dimension to a target tensor 
- Permute: Return a view of input with dimensions permuted (swapped) in a certain way 

#### i. Reshaping 
Allows us to change the dimension of our tensor. Usually the row and column specification of the resphase should be multiples of the size of the tensor

In [50]:
tensor_A

tensor([[34,  5,  6,  3],
        [ 3,  2,  5,  6],
        [ 7,  8,  9, 10]])

In [51]:
torch.reshape(tensor_A, shape= (4,3))

tensor([[34,  5,  6],
        [ 3,  3,  2],
        [ 5,  6,  7],
        [ 8,  9, 10]])

In [52]:
 tensor_A.reshape(6,2)


tensor([[34,  5],
        [ 6,  3],
        [ 3,  2],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [53]:
 tensor_A.reshape(1,12)


tensor([[34,  5,  6,  3,  3,  2,  5,  6,  7,  8,  9, 10]])

#### Stacking

In [54]:
stack= torch.stack([tensor_A, tensor_B], dim=0)
stack

tensor([[[34,  5,  6,  3],
         [ 3,  2,  5,  6],
         [ 7,  8,  9, 10]],

        [[ 4,  5,  6,  3],
         [ 9,  9,  9, 10],
         [12,  8,  9, 10]]])

In [55]:
h_stack= torch.hstack([tensor_A, tensor_B])
h_stack

tensor([[34,  5,  6,  3,  4,  5,  6,  3],
        [ 3,  2,  5,  6,  9,  9,  9, 10],
        [ 7,  8,  9, 10, 12,  8,  9, 10]])

In [56]:
V_stack=torch.vstack([tensor_A, tensor_B])
V_stack

tensor([[34,  5,  6,  3],
        [ 3,  2,  5,  6],
        [ 7,  8,  9, 10],
        [ 4,  5,  6,  3],
        [ 9,  9,  9, 10],
        [12,  8,  9, 10]])

#### Squeezing and UnSqueezin

In [57]:
tensor_A

tensor([[34,  5,  6,  3],
        [ 3,  2,  5,  6],
        [ 7,  8,  9, 10]])

In [58]:
tensor_A.unsqueeze(dim=2)

tensor([[[34],
         [ 5],
         [ 6],
         [ 3]],

        [[ 3],
         [ 2],
         [ 5],
         [ 6]],

        [[ 7],
         [ 8],
         [ 9],
         [10]]])

In [59]:
torch.manual_seed(23)
t4= torch.rand(1,2,4,5)

print(f"The shape of {t4} is: {t4.shape}")

The shape of tensor([[[[0.4283, 0.2889, 0.4224, 0.3571, 0.9577],
          [0.1100, 0.2933, 0.9205, 0.5876, 0.1299],
          [0.6729, 0.1028, 0.7876, 0.5540, 0.4653],
          [0.2311, 0.2214, 0.3348, 0.4541, 0.2519]],

         [[0.6310, 0.1707, 0.3122, 0.1976, 0.5466],
          [0.0213, 0.9049, 0.8444, 0.9330, 0.2950],
          [0.4773, 0.4787, 0.3440, 0.6732, 0.6593],
          [0.1879, 0.4546, 0.1049, 0.7112, 0.7709]]]]) is: torch.Size([1, 2, 4, 5])


In [60]:
squeezed_t4= t4.squeeze()

print(f"The shape of {squeezed_t4} is: {squeezed_t4.shape}")

The shape of tensor([[[0.4283, 0.2889, 0.4224, 0.3571, 0.9577],
         [0.1100, 0.2933, 0.9205, 0.5876, 0.1299],
         [0.6729, 0.1028, 0.7876, 0.5540, 0.4653],
         [0.2311, 0.2214, 0.3348, 0.4541, 0.2519]],

        [[0.6310, 0.1707, 0.3122, 0.1976, 0.5466],
         [0.0213, 0.9049, 0.8444, 0.9330, 0.2950],
         [0.4773, 0.4787, 0.3440, 0.6732, 0.6593],
         [0.1879, 0.4546, 0.1049, 0.7112, 0.7709]]]) is: torch.Size([2, 4, 5])


- From above, the shapes are different 

In [61]:
## unsqueeze: We will use the squeezed t4 as an exaample 

## the dim tells us the position to which we can add the new dimension of size 1, I will create an extra with the changed dim to demonstrate this 

unsqueezed_t4= squeezed_t4.unsqueeze(dim=3)
unsqueezed_t4_2= squeezed_t4.unsqueeze(dim=2)




In [62]:
##we will just print the shape to see how they shapes vary from the original tensor: 

print(f"The shape of t4 is: {t4.shape}")
print(f"The shape of squeezed_t4 is: {squeezed_t4.shape}")
print(f"The shape of unsqueezed_t4 is: {unsqueezed_t4.shape}")
print(f"The shape of unsqueezed_t4_2 is: {unsqueezed_t4_2.shape}")



The shape of t4 is: torch.Size([1, 2, 4, 5])
The shape of squeezed_t4 is: torch.Size([2, 4, 5])
The shape of unsqueezed_t4 is: torch.Size([2, 4, 5, 1])
The shape of unsqueezed_t4_2 is: torch.Size([2, 4, 1, 5])


#### Permutation 

- Permutation allows us to change the orientation of the values of a matrix 

In [63]:
torch.manual_seed(33) ## to ensure consistency

x_original= torch.rand(size=(2,4,3))

x_permute= torch.permute(x_original, (2,0,1))

In [64]:
print(f"The original shape of x_original is {x_original.shape}")
print(f"The permute shape of x_original is {x_permute.shape}")



The original shape of x_original is torch.Size([2, 4, 3])
The permute shape of x_original is torch.Size([3, 2, 4])


### Indexing

- Indexing in Pytorch is simlar to indexing in Numpy

In [65]:
x= torch.arange(1,13).reshape(1,4,3)

x, x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9],
          [10, 11, 12]]]),
 torch.Size([1, 4, 3]))

Extract the following:

- First row 
- number 7, and 1
- second and third row 

In [66]:
##indexing the first row 

x[:, 0]

tensor([[1, 2, 3]])

In [67]:
##extracting numbers 7,

x[0][2][0]

tensor(7)

In [68]:
##extracting the number 11

x[0][3][1]

tensor(11)

In [69]:
##extracting the first two rows 

x[:,1:3]


tensor([[[4, 5, 6],
         [7, 8, 9]]])

### Pytorch, Tensors and Numpy 

This section focused on teaching how to get data from `numpy` and use it in `pytorch` or vice versa

- To use `Numpy` in `Pytorch`, you use the: `torch.from_numpy(ndarray)`
- To use `PyTorch` tensor, you use the `torch.Tensor.numpy()`

In [70]:
import numpy as np

np_array= np.array([[2,3,4,5], [2,4,23,2]])

print(np_array.dtype)

int64


In [71]:
##changing a numpy array to a tensor 

np_array_tensor= torch.from_numpy(np_array)

In [72]:
print(f"The datatype of the numpy array is {np_array.dtype}.")
print(f"The datatype of the Pytorch tensor is {np_array_tensor.dtype}.")

The datatype of the numpy array is int64.
The datatype of the Pytorch tensor is torch.int64.


In [73]:
##changing a tensor to an array 

ten_to_np_array=torch.Tensor.numpy(tensor_A)

In [74]:
print(f"The datatype of the numpy array is {tensor_A.dtype}.")
print(f"The datatype of the Pytorch tensor is {ten_to_np_array.dtype}.")

The datatype of the numpy array is torch.int64.
The datatype of the Pytorch tensor is int64.


### Pytorch Reproducability 

- If you noticed I used some sort of `manual_seed` in some of my codes where I used the rand variable. Well this is because, I didn't want the value changing each time I run my code
- This is also important in cases where you want to share your code with others and ensure that you both have the same values  

In [75]:
torch.manual_seed(123)

tensor_static= torch.randn(2,3,4)



In [76]:
tensor_static

tensor([[[ 0.3374, -0.1778, -0.3035, -0.5880],
         [ 0.3486,  0.6603, -0.2196, -0.3792],
         [-0.1606, -0.4015,  0.6957, -1.8061]],

        [[ 1.8960, -0.1750,  1.3689, -1.6033],
         [-0.7849, -1.4096, -0.4076,  0.7953],
         [ 0.9985,  0.2212,  1.8319, -0.3378]]])

In [77]:
torch.randn(2,3,4)


tensor([[[ 0.9624,  0.2492, -0.4845, -2.0929],
         [-0.8199, -0.4210, -0.9620,  1.2825],
         [ 0.5146,  0.9938, -0.2587, -1.0826]],

        [[-0.0444,  1.6236, -2.3229,  1.0878],
         [ 0.6716,  0.6933, -0.9487, -0.0765],
         [-0.1526,  0.1167,  0.4403, -1.4465]]])

In [78]:
torch.randn(2,3,4)


tensor([[[ 0.2553, -0.5496,  1.0042,  0.8272],
         [-0.3948,  0.4892, -0.2168, -1.7472],
         [ 0.0475, -0.9239, -1.0607, -2.3244]],

        [[ 1.2311, -1.0973, -0.9669,  0.6712],
         [-0.9822,  0.2770,  0.6455, -0.8957],
         [ 1.1124, -0.4168, -1.7106, -0.3290]]])

In [79]:
tensor_static

tensor([[[ 0.3374, -0.1778, -0.3035, -0.5880],
         [ 0.3486,  0.6603, -0.2196, -0.3792],
         [-0.1606, -0.4015,  0.6957, -1.8061]],

        [[ 1.8960, -0.1750,  1.3689, -1.6033],
         [-0.7849, -1.4096, -0.4076,  0.7953],
         [ 0.9985,  0.2212,  1.8319, -0.3378]]])

### Summary 
- So, we can see the tensor-static stays the same 
- But the second and third changes 
- The `torch.manual_seed` only affects the cell it is in 

### Accessing GPU In PyTorch 

In [ ]:
### Creating some tensors and setting them to the device 

def create_torch_tensors(device):
    x= torch.rand((10000, 10000), dtype=torch.float32)
    y= torch.rand((10000, 10000), dtype=torch.float32)
    x= x.to(device)
    y= y.to(device)

    return x,y 

In [ ]:
##setting the cpu as my device 
device= torch.device("cpu")
x,y= create_torch_tensors(device)

In [ ]:
##perfoming matrix multiplication with cpu
%%timeit
x*y

19.1 ms ± 740 μs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
##setting GPU as device 
device= torch.device("mps")
x,y= create_torch_tensors(device)


In [ ]:
##performing matrix multiplication with GPU 
%%timeit
x*y

9.41 ms ± 43.8 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [89]:
##Check for GPU access with Pytorch 

torch.backends.mps.is_built()

True

In [90]:
## setting my mps as device

device = torch.device("mps") if torch.backends.mps.is_available() else torch.device("cpu")
print(f"Using device: {device}")

Using device: mps
